apiVersion: v1
kind: ConfigMap
metadata:
  name: k3sapi-config
data:
  APP_ENV: "dev"
  APP_PORT: "4000"

---
apiVersion: v1
kind: Secret
metadata:
  name: k3sapi-secret
type: Opaque
stringData:
  PWD: "example_pwd"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3sapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k3sapi
  template:
    metadata:
      labels:
        app: k3sapi
    spec:
      containers:
        - name: k3s-api-container
          image: leoff00/k3s-api:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: k3sapi-config
            - secretRef:
                name: k3sapi-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
      # volumes:
      #  ========== if i want to make a CI/CD deploy, inject this + secretproviderclass yaml + serviceAccount
      #   - name: vol
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "k3sapi-secrets"

---
apiVersion: v1
kind: Service
metadata:
  name: k3sapi-service
spec:
  selector:
    app: k3sapi
  type: LoadBalancer
  ports:
    - name: http
      port: 4000
      targetPort: 4000

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-debugger
spec:
  selector:
    matchLabels:
      app: node-debugger
  template:
    metadata:
      labels:
        app: node-debugger
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            [
              "/bin/sh",
              "-c",
              "while true; do echo 'running on node'; sleep 10; done",
            ]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k3sapi-stateful
spec:
  serviceName: "k3sapi-stateful"
  replicas: 3
  selector:
    matchLabels:
      app: k3sapi-stateful
  template:
    metadata:
      labels:
        app: k3sapi-stateful
    spec:
      containers:
        - name: k3sapi
          image: leoff00/k3s-api:latest
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
