apiVersion: v1
kind: ConfigMap
metadata:
  name: k3sapi-config
data:
  APP_ENV: "dev"
  APP_PORT: "4000"

---
apiVersion: v1
kind: Secret
metadata:
  name: k3sapi-secret
type: Opaque
stringData:
  PWD: "example_pwd"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3sapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k3sapi
  template:
    metadata:
      labels:
        app: k3sapi
    spec:
      containers:
        - name: k3s-api-container
          image: leoff00/k3s-api:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: k3sapi-config
            - secretRef:
                name: k3sapi-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: k3sapi-service
spec:
  selector:
    app: k3sapi
  type: LoadBalancer
  ports:
    - name: http
      port: 4000
      targetPort: 4000
